<?php

namespace Database\Seeders;

use App\Domain\Property\Property;
use App\Models\PropertyImage;
use Illuminate\Database\Seeder;
use Illuminate\Support\Collection;

class PropertySeeder extends Seeder
{
    private array $properties = [
        // Host 1 (João) — 5 imóveis RJ/SP
        [
            'host_index' => 0,
            'title' => 'Cobertura Luxo com Vista para o Mar',
            'type' => 'entire_place',
            'description' => 'Deslumbrante cobertura com vista panorâmica para o mar de Copacabana. Ambientes amplos e sofisticados, piscina privativa e acabamento de alto padrão. Perfeita para quem busca luxo e conforto.',
            'address' => 'Av. Atlântica, 1500',
            'city' => 'Rio de Janeiro',
            'state' => 'RJ',
            'property_type' => 'apartment',
            'price_per_night' => 1200.00,
            'cleaning_fee' => 250.00,
            'max_guests' => 6,
            'bedrooms' => 3,
            'bathrooms' => 3,
            'latitude' => -22.9711,
            'longitude' => -43.1823,
            'images' => ['https://images.unsplash.com/photo-1522708323590-d24dbb6b0267', 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688'],
        ],
        [
            'host_index' => 0,
            'title' => 'Apartamento Moderno no Centro',
            'type' => 'entire_place',
            'description' => 'Apartamento totalmente reformado no coração da Av. Paulista. Próximo a restaurantes, museus e estações de metrô. Internet de alta velocidade e home office preparado.',
            'address' => 'Av. Paulista, 1000',
            'city' => 'São Paulo',
            'state' => 'SP',
            'property_type' => 'apartment',
            'price_per_night' => 350.00,
            'cleaning_fee' => 80.00,
            'max_guests' => 3,
            'bedrooms' => 2,
            'bathrooms' => 1,
            'latitude' => -23.5614,
            'longitude' => -46.6561,
            'images' => ['https://images.unsplash.com/photo-1560448204-e02f11c3d0e2', 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267'],
        ],
        [
            'host_index' => 0,
            'title' => 'Flat Elegante no Leblon',
            'type' => 'entire_place',
            'description' => 'Flat sofisticado no coração do Leblon, a uma quadra da praia. Decoração assinada, cozinha equipada e serviço de concierge 24h. Ideal para viagens a negócios ou lazer.',
            'address' => 'Rua Ataulfo de Paiva, 500',
            'city' => 'Rio de Janeiro',
            'state' => 'RJ',
            'property_type' => 'apartment',
            'price_per_night' => 890.00,
            'cleaning_fee' => 180.00,
            'max_guests' => 4,
            'bedrooms' => 2,
            'bathrooms' => 2,
            'latitude' => -22.9833,
            'longitude' => -43.2244,
            'images' => ['https://images.unsplash.com/photo-1586023492125-27b2c045efd7', 'https://images.unsplash.com/photo-1560185007-cde436f6a4d0'],
        ],
        [
            'host_index' => 0,
            'title' => 'Apartamento com Vista para o Pão de Açúcar',
            'type' => 'entire_place',
            'description' => 'Apartamento em Niterói com vista deslumbrante para o Pão de Açúcar e a Baía de Guanabara. Sala ampla, varanda gourmet e academia no condomínio.',
            'address' => 'Av. Beira Mar, 300',
            'city' => 'Niterói',
            'state' => 'RJ',
            'property_type' => 'apartment',
            'price_per_night' => 450.00,
            'cleaning_fee' => 100.00,
            'max_guests' => 5,
            'bedrooms' => 3,
            'bathrooms' => 2,
            'latitude' => -22.8838,
            'longitude' => -43.1159,
            'images' => ['https://images.unsplash.com/photo-1560184897-ae75f418493e', 'https://images.unsplash.com/photo-1560185007-b5a6e1c7b9e8'],
        ],
        [
            'host_index' => 0,
            'title' => 'Studio Completo nos Jardins',
            'type' => 'entire_place',
            'description' => 'Studio compacto e funcional no bairro dos Jardins em São Paulo. Cama queen-size, cozinha americana e varanda. Proximo ao Parque do Ibirapuera e restaurantes premiados.',
            'address' => 'Rua Oscar Freire, 800',
            'city' => 'São Paulo',
            'state' => 'SP',
            'property_type' => 'studio',
            'price_per_night' => 320.00,
            'cleaning_fee' => 70.00,
            'max_guests' => 2,
            'bedrooms' => 1,
            'bathrooms' => 1,
            'latitude' => -23.5667,
            'longitude' => -46.6708,
            'images' => ['https://images.unsplash.com/photo-1598928506311-c55ez637a11a', 'https://images.unsplash.com/photo-1585412727339-54e4bae3bbf9'],
        ],
        // Host 2 (Maria) — 5 imóveis litorâneos/natureza
        [
            'host_index' => 1,
            'title' => 'Chalé Aconchegante na Serra',
            'type' => 'entire_place',
            'description' => 'Chalé rústico rodeado pela natureza da Serra da Mantiqueira. Lareira a lenha, hidromassagem externa e café colonial incluso. Ideal para casais em busca de romance e tranquilidade.',
            'address' => 'Estrada do Pico, Km 12',
            'city' => 'Campos do Jordão',
            'state' => 'SP',
            'property_type' => 'cabin',
            'price_per_night' => 580.00,
            'cleaning_fee' => 120.00,
            'max_guests' => 4,
            'bedrooms' => 2,
            'bathrooms' => 1,
            'latitude' => -22.7392,
            'longitude' => -45.5914,
            'images' => ['https://images.unsplash.com/photo-1518780664697-55e3ad937233', 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4'],
        ],
        [
            'host_index' => 1,
            'title' => 'Casa com Piscina em Condomínio',
            'type' => 'entire_place',
            'description' => 'Casa ampla em condomínio fechado com segurança 24h. Piscina, churrasqueira e área de lazer completa. Perfeita para famílias e grupos de amigos.',
            'address' => 'Rua das Flores, 500',
            'city' => 'Florianópolis',
            'state' => 'SC',
            'property_type' => 'house',
            'price_per_night' => 780.00,
            'cleaning_fee' => 180.00,
            'max_guests' => 10,
            'bedrooms' => 4,
            'bathrooms' => 3,
            'latitude' => -27.5969,
            'longitude' => -48.5495,
            'images' => ['https://images.unsplash.com/photo-1564013799919-ab600027ffc6', 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750'],
        ],
        [
            'host_index' => 1,
            'title' => 'Studio Pé na Areia em Porto de Galinhas',
            'type' => 'entire_place',
            'description' => 'Studio completo bem em frente à praia de Porto de Galinhas. Varanda com rede, cozinha compacta e ar condicionado. O melhor custo-benefício para curtir o litoral pernambucano.',
            'address' => 'Rodovia PE-09, s/n',
            'city' => 'Ipojuca',
            'state' => 'PE',
            'property_type' => 'studio',
            'price_per_night' => 420.00,
            'cleaning_fee' => 90.00,
            'max_guests' => 2,
            'bedrooms' => 1,
            'bathrooms' => 1,
            'latitude' => -8.5034,
            'longitude' => -35.0028,
            'images' => ['https://images.unsplash.com/photo-1596394516093-501ba68a0ba6', 'https://images.unsplash.com/photo-1566073771259-6a8506099945'],
        ],
        [
            'host_index' => 1,
            'title' => 'Bangalô com Rede na Praia do Rosa',
            'type' => 'entire_place',
            'description' => 'Bangalô ecológico a 100m da Praia do Rosa. Construído com materiais sustentáveis, energia solar e captação de água da chuva. Café da manhã orgânico incluso.',
            'address' => 'Estrada Geral da Praia do Rosa, s/n',
            'city' => 'Imbituba',
            'state' => 'SC',
            'property_type' => 'cottage',
            'price_per_night' => 520.00,
            'cleaning_fee' => 110.00,
            'max_guests' => 4,
            'bedrooms' => 2,
            'bathrooms' => 1,
            'latitude' => -28.1353,
            'longitude' => -48.6542,
            'images' => ['https://images.unsplash.com/photo-1600585154340-be6161a56a0c', 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9'],
        ],
        [
            'host_index' => 1,
            'title' => 'Bangalô em Trancoso',
            'type' => 'entire_place',
            'description' => 'Bangalô charmoso no Quadrado de Trancoso, com vista para o mar e o centrinho histórico. Piscina privativa, decoração boho-chic e café da manhã colonial incluso.',
            'address' => 'Rua do Quadrado, s/n',
            'city' => 'Porto Seguro',
            'state' => 'BA',
            'property_type' => 'cottage',
            'price_per_night' => 680.00,
            'cleaning_fee' => 150.00,
            'max_guests' => 4,
            'bedrooms' => 2,
            'bathrooms' => 2,
            'latitude' => -16.5927,
            'longitude' => -39.0933,
            'images' => ['https://images.unsplash.com/photo-1571896349842-33c89424de2d', 'https://images.unsplash.com/photo-1568084680786-a84f91d1153c'],
        ],
        // Host 3 (Carlos) — 5 imóveis alto padrão
        [
            'host_index' => 2,
            'title' => 'Villa Climatizada com Vistas Incríveis',
            'type' => 'entire_place',
            'description' => 'Villa contemporânea com design assinado, piscina de borda infinita e vista deslumbrante para as montanhas. 4 suítes, adega climatizada e serviço de mordomo disponível.',
            'address' => 'Rua das Paineiras, 200',
            'city' => 'Brotas',
            'state' => 'SP',
            'property_type' => 'villa',
            'price_per_night' => 1500.00,
            'cleaning_fee' => 350.00,
            'max_guests' => 8,
            'bedrooms' => 4,
            'bathrooms' => 4,
            'latitude' => -22.2848,
            'longitude' => -48.1271,
            'images' => ['https://images.unsplash.com/photo-1600596542815-ffad4c1539a9', 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c'],
        ],
        [
            'host_index' => 2,
            'title' => 'Quarto Privativo em Casa Compartilhada',
            'type' => 'private_room',
            'description' => 'Quarto privativo em casa compartilhada no bairro boêmio da Vila Madalena. Ideal para nômade digital com espaços de coworking, café da manhã incluso e convivência com moradores locais.',
            'address' => 'Rua Harmonia, 123',
            'city' => 'São Paulo',
            'state' => 'SP',
            'property_type' => 'house',
            'price_per_night' => 120.00,
            'cleaning_fee' => 30.00,
            'max_guests' => 2,
            'bedrooms' => 1,
            'bathrooms' => 1,
            'latitude' => -23.5531,
            'longitude' => -46.6944,
            'images' => ['https://images.unsplash.com/photo-1560448204-e02f11c3d0e2'],
        ],
        [
            'host_index' => 2,
            'title' => 'Cobertura com Piscina Aquecida',
            'type' => 'entire_place',
            'description' => 'Cobertura duplex de 400m² no alto do Morumbi com piscina aquecida, academia privativa e home theater. Acabamento顶级 e automação residencial completa.',
            'address' => 'Av. Morumbi, 5000',
            'city' => 'São Paulo',
            'state' => 'SP',
            'property_type' => 'apartment',
            'price_per_night' => 2100.00,
            'cleaning_fee' => 400.00,
            'max_guests' => 8,
            'bedrooms' => 4,
            'bathrooms' => 4,
            'latitude' => -23.6136,
            'longitude' => -46.7194,
            'images' => ['https://images.unsplash.com/photo-1600210492486-724fe5c67fb0', 'https://images.unsplash.com/photo-1600566753086-00f18f6b7e6a'],
        ],
        [
            'host_index' => 2,
            'title' => 'Casa com Quadra de Tênis',
            'type' => 'entire_place',
            'description' => 'Casarão em condomínio de alto padrão em Campinas com quadra de tênis, piscina olímpica e salão de festas. Ideal para eventos corporativos e encontros familiares.',
            'address' => 'Alphaville Campinas, Al. Terracota, 100',
            'city' => 'Campinas',
            'state' => 'SP',
            'property_type' => 'house',
            'price_per_night' => 1350.00,
            'cleaning_fee' => 300.00,
            'max_guests' => 12,
            'bedrooms' => 5,
            'bathrooms' => 4,
            'latitude' => -22.9071,
            'longitude' => -47.0595,
            'images' => ['https://images.unsplash.com/photo-1600596542815-ffad4c1539a9', 'https://images.unsplash.com/photo-1600585154526-990dced4db0d'],
        ],
        [
            'host_index' => 2,
            'title' => 'Loft Contemporâneo no Centro',
            'type' => 'entire_place',
            'description' => 'Loft minimalista no coração de Belo Horizonte, próximo à Praça da Liberdade. Pés-direito duplo, paredes de vidro e mobiliário de design. Internet gigabit para home office.',
            'address' => 'Rua da Bahia, 1500',
            'city' => 'Belo Horizonte',
            'state' => 'MG',
            'property_type' => 'loft',
            'price_per_night' => 380.00,
            'cleaning_fee' => 80.00,
            'max_guests' => 3,
            'bedrooms' => 1,
            'bathrooms' => 1,
            'latitude' => -19.9321,
            'longitude' => -43.9371,
            'images' => ['https://images.unsplash.com/photo-1536376072261-38c75010e6c9', 'https://images.unsplash.com/photo-1600585154526-990dced4db0d'],
        ],
        // Host 4 (Ana) — 5 imóveis diversificados
        [
            'host_index' => 3,
            'title' => 'Loft Industrial com Mezanino',
            'type' => 'entire_place',
            'description' => 'Loft decorado em estilo industrial no bairro de Santa Teresa. Pés-direito duplo, mezanino com cama king-size e vista para o Centro do Rio. Experiência única de hospedagem.',
            'address' => 'Rua do Curvelo, 50',
            'city' => 'Rio de Janeiro',
            'state' => 'RJ',
            'property_type' => 'loft',
            'price_per_night' => 490.00,
            'cleaning_fee' => 100.00,
            'max_guests' => 3,
            'bedrooms' => 1,
            'bathrooms' => 1,
            'latitude' => -22.9193,
            'longitude' => -43.1882,
            'images' => ['https://images.unsplash.com/photo-1536376072261-38c75010e6c9', 'https://images.unsplash.com/photo-1600585154526-990dced4db0d'],
        ],
        [
            'host_index' => 3,
            'title' => 'Casa Colonial Histórica em Paraty',
            'type' => 'entire_place',
            'description' => 'Casa colonial do século XVIII totalmente restaurada no centro histórico de Paraty. Pátio interno com fontes, jardim tropical e decoração de época combinada com conforto moderno.',
            'address' => 'Rua do Comércio, 80',
            'city' => 'Paraty',
            'state' => 'RJ',
            'property_type' => 'house',
            'price_per_night' => 650.00,
            'cleaning_fee' => 140.00,
            'max_guests' => 6,
            'bedrooms' => 3,
            'bathrooms' => 2,
            'latitude' => -23.2226,
            'longitude' => -44.7175,
            'images' => ['https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf', 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3'],
        ],
        [
            'host_index' => 3,
            'title' => 'Cobertura com Vista para o Mar em Salvador',
            'type' => 'entire_place',
            'description' => 'Cobertura panorâmica no bairro da Barra com vista de 180° para o mar. Piscina privativa, varanda com ofurô e nascer do sol deslumbrante sobre o Farol da Barra.',
            'address' => 'Av. Oceânica, 2000',
            'city' => 'Salvador',
            'state' => 'BA',
            'property_type' => 'apartment',
            'price_per_night' => 750.00,
            'cleaning_fee' => 160.00,
            'max_guests' => 5,
            'bedrooms' => 3,
            'bathrooms' => 2,
            'latitude' => -13.0068,
            'longitude' => -38.5335,
            'images' => ['https://images.unsplash.com/photo-1560185007-cde436f6a4d0', 'https://images.unsplash.com/photo-1560184897-ae75f418493e'],
        ],
        [
            'host_index' => 3,
            'title' => 'Casinha na Árvore com Vista para as Montanhas',
            'type' => 'entire_place',
            'description' => 'Hospedagem única em uma casa na árvore construída sobre um pinheiro centenário em Urubici. Vista panorâmica da serra, lareira e banheira de hidromassagem ao ar livre.',
            'address' => 'Estrada do Morro da Igreja, Km 8',
            'city' => 'Urubici',
            'state' => 'SC',
            'property_type' => 'cabin',
            'price_per_night' => 480.00,
            'cleaning_fee' => 90.00,
            'max_guests' => 2,
            'bedrooms' => 1,
            'bathrooms' => 1,
            'latitude' => -28.0165,
            'longitude' => -49.5912,
            'images' => ['https://images.unsplash.com/photo-1510798831971-661eb04b3739', 'https://images.unsplash.com/photo-1473625247510-8ceb1760943f'],
        ],
        [
            'host_index' => 3,
            'title' => 'Casa Sede em Fazenda Histórica',
            'type' => 'entire_place',
            'description' => 'Casa sede do século XIX em fazenda histórica em Monte Verde. Lareiras originais, jardim inglês, cavalgadas e café da manhã com produtos da fazenda. Experiência rural completa.',
            'address' => 'Fazenda das Flores, Estrada Municipal, s/n',
            'city' => 'Monte Verde',
            'state' => 'MG',
            'property_type' => 'house',
            'price_per_night' => 550.00,
            'cleaning_fee' => 120.00,
            'max_guests' => 8,
            'bedrooms' => 4,
            'bathrooms' => 3,
            'latitude' => -22.8614,
            'longitude' => -46.0414,
            'images' => ['https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf', 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3'],
        ],
    ];

    public function run(Collection $hosts): void
    {
        foreach ($this->properties as $data) {
            $hostIndex = $data['host_index'];
            $images = $data['images'];
            unset($data['host_index'], $data['images']);

            $slug = str($data['title'])->slug()->append('-' . fake()->unique()->randomNumber(4));

            $property = Property::factory()->create(
                array_merge($data, [
                    'host_id' => $hosts->get($hostIndex)->id,
                    'slug' => $slug->value(),
                    'status' => 'available',
                    'check_in_time' => '14:00:00',
                    'check_out_time' => '11:00:00',
                ])
            );

            foreach ($images as $i => $imageUrl) {
                PropertyImage::factory()->create([
                    'property_id' => $property->id,
                    'image_url' => $imageUrl . '?w=800&h=600&fit=crop',
                    'is_cover' => $i === 0,
                    'order' => $i,
                ]);
            }
        }
    }
}
